spring.application.name=SafeRent Backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/saferent}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:saferent}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:saferent_dev_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
